tws:
  image: ib
  ports:
    - "4003:4003"
    - "5900:5900"
  environment:
    - TZ=America/New_York
    # Variables pulled from /IBController/IBControllerGatewayStart.sh
    - VNC_PASSWORD=password
    - TWS_MAJOR_VRSN=960
    - IBC_INI=/root/IBController/IBController.ini
    - TRADING_MODE=${IB_TRADING_MODE}
    - IBC_PATH=/opt/IBController
    - TWS_PATH=/root/Jts
    - TWS_CONFIG_PATH=/root/Jts
    - LOG_PATH=/opt/IBController/Logs
    - TWSUSERID=${IB_USER}
    - TWSPASSWORD=${IB_PASSWORD}
    - FIXUSERID=
    - FIXPASSWORD=
    - JAVA_PATH=
    - APP=GATEWAY
